<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 1/31/18
 * Time: 8:11 PM
 */

class Model_Admin extends Model
{
   public function get_data()
   {
       parent::get_data(); // TODO: Change the autogenerated stub
   }
}